#!/usr/bin/env python3
import click
from pathlib import Path

# import CLI arguments
from .command_arguments.out import out_option
from .command_arguments.confluence import confluence_option
from .command_arguments.llm_summary import ai_summary_option  # renamed file but same path

# utils
from .utils.file_finder import find_action_files
from .utils.yaml_loader import parse_action_yaml
from .utils.ollama import ollama_summarize
from .utils.workflow_finder import find_workflow_files

# renderers
from .renderers import branding, inputs, outputs, runs, permissions, env, defaults
from .renderers.workflow_markdown import render_workflow_doc


@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@out_option
@confluence_option
@ai_summary_option
@click.option("--path", "-p", type=click.Path(exists=True, path_type=Path), default=Path("."), help="Root directory.")
@click.option("--actions", is_flag=True, help="Generate docs for all GitHub Actions (action.yml files).")
@click.option("--action", type=click.Path(exists=True, path_type=Path), help="Generate docs for a single Action file.")
@click.option("--workflows", is_flag=True, help="Generate docs for all workflow YAML files.")
@click.option("--workflow", type=click.Path(exists=True, path_type=Path), help="Generate docs for a single workflow file.")
@click.version_option(message="cifolio %(version)s")
def cli(path, out, confluence, ai_summary, model, actions, action, workflows, workflow):
    """Generate Markdown docs from GitHub Actions and Workflows."""

    out.mkdir(parents=True, exist_ok=True)
    docs = []

    # ---------------- ACTIONS ----------------
    if actions or action:
        action_files = [action] if action else find_action_files(path)
        if not action_files:
            click.echo(f"No action.yml/.yaml found under: {path}", err=True)
        for f in action_files:
            try:
                data = parse_action_yaml(f)
            except Exception as e:
                click.echo(f"ERROR parsing {f}: {e}", err=True)
                continue

            name = data.get("name", f.stem)
            desc = data.get("description", "")
            author = data.get("author", "")

            md = [f"# {name}\n"]
            if desc:
                md.append(desc + "\n")
            else:
                # generate description via AI if no description field
                if ai_summary:
                    summary = ollama_summarize(data, model=model)
                    md.append(f"> {summary}\n")

            if ai_summary and desc:
                summary = ollama_summarize(data, model=model)
                md.append(f"> {summary}\n")

            md.append(f"**File:** `{f}`  ")
            if author:
                md.append(f"**Author:** `{author}`  ")
            md.append("\n## Branding\n" + branding.render(data.get("branding", {})))
            md.append("\n## Inputs\n" + inputs.render(data.get("inputs", {})))
            md.append("\n## Outputs\n" + outputs.render(data.get("outputs", {})))
            md.append("\n## Runs\n" + runs.render(data.get("runs", {})))
            md.append("\n## Permissions\n" + permissions.render(data.get("permissions", {})))
            md.append("\n## Env\n" + env.render(data.get("env", {})))
            md.append("\n## Defaults\n" + defaults.render(data.get("defaults", {})))
            md.append("\n---\n_Generated by cifolio_")

            docs.append((f, name, "\n".join(md)))

    # ---------------- WORKFLOWS ----------------
    if workflows or workflow:
        workflow_files = [workflow] if workflow else find_workflow_files(path)
        if not workflow_files:
            click.echo(f"No workflow YAML found under: {path}", err=True)
        for wf in workflow_files:
            try:
                data = parse_action_yaml(wf)
            except Exception as e:
                click.echo(f"ERROR parsing {wf}: {e}", err=True)
                continue
            if not isinstance(data, dict) or "on" not in data:
                continue

            name = data.get("name", wf.stem)
            md = render_workflow_doc(
                data=data,
                file_path=wf,
                llm_summary=ai_summary,
                llm_model=model,
                summarize_fn=ollama_summarize if ai_summary else None,
            )
            docs.append((wf, name, md))

    # ---------------- WRITE OUTPUT ----------------
    if not docs:
        click.echo("No documentation generated.")
        raise SystemExit(2)

    index_lines = ["# CIfolio — Documentation Index", ""]
    for f, name, md in docs:
        safe_name = name.replace(" ", "_").replace("/", "_")
        md_filename = f"{safe_name}.md"
        (out / md_filename).write_text(md, encoding="utf-8")
        index_lines.append(f"- [{name}]({md_filename}) — `{f}`")

    (out / "INDEX.md").write_text("\n".join(index_lines), encoding="utf-8")
    click.echo(f"Wrote {out / 'INDEX.md'} and {len(docs)} file(s) to {out}")
